name: Build

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      disable-cache:
        required: false
        type: boolean
        default: false

jobs:
  build-windows:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            artifactName: windows-x86_64
            arch: x86_64

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: ${{ inputs.disable-cache }}

      - name: Build project
        run: ./gradlew packageReleaseMsi

      - name: Rename & move artifact
        shell: bash
        run: mv composeApp/build/compose/binaries/main-release/msi/qBitController-*.msi "qbitcontroller-${{ inputs.version }}-windows-${{ matrix.arch }}.msi"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifactName }}
          path: "qbitcontroller-${{ inputs.version }}-windows-${{ matrix.arch }}.msi"